# Generated by Django 5.0.2 on 2024-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_managerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("MANAGER", "manager"),
                    ("STUDENT", "student"),
                ],
                default="ADMIN",
                max_length=50,
            ),
        ),
    ]
