# Generated by Django 5.0.2 on 2024-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_studentprofile_user_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.PositiveIntegerField(max_length=9, null=True, unique=True),
        ),
    ]
