# Generated by Django 5.0.2 on 2024-04-20 15:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.PositiveIntegerField(
                null=True, unique=True, validators=[accounts.models.validate_length]
            ),
        ),
    ]
