# Generated by Django 4.2.11 on 2024-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "admin"),
                    ("MANAGER", "manager"),
                    ("STUDENT", "student"),
                ],
                default="STUDENT",
                max_length=50,
                null=True,
            ),
        ),
    ]
