# Generated by Django 5.0.2 on 2024-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_imgage",
            field=models.ImageField(
                blank=True,
                default="static/images/aqsa.jpeg",
                upload_to="static/images/event_images",
            ),
        ),
    ]
