# Generated by Django 5.0.2 on 2024-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0002_event_event_imgage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_imgage",
            field=models.ImageField(
                blank=True, default="media/aqsa.jpeg", upload_to="event_images"
            ),
        ),
    ]
