# Generated by Django 5.0.2 on 2024-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0006_alter_event_event_imgage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("club", models.CharField(max_length=70)),
                ("date", models.DateTimeField(blank=True)),
                ("location", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(max_length=15)),
                ("event_content", models.TextField()),
                ("speakers", models.TextField()),
                ("place", models.CharField(max_length=70)),
                ("special_services", models.TextField()),
                ("other_reqests", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=30)),
                (
                    "club_imgage",
                    models.ImageField(
                        blank=True, default="club_default.jpeg", upload_to="club_images"
                    ),
                ),
                (
                    "club_cover",
                    models.ImageField(
                        blank=True,
                        default="club_cover_default.jpeg",
                        upload_to="club_images",
                    ),
                ),
            ],
        ),
    ]
