# Generated by Django 5.0.2 on 2024-04-20 16:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0008_club_about_club_manager_club_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="purpose",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="vice_first_name",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="vice_last_name",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="body",
            field=ckeditor.fields.RichTextField(max_length=10),
        ),
    ]
