# Generated by Django 5.0.2 on 2024-04-21 19:37

import club_pages.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0010_club_author_alter_event_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="club_cover",
            field=models.ImageField(
                blank=True, default="club_cover_default.png", upload_to="club_images"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="manager",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                validators=[club_pages.models.validate_manager_role],
            ),
        ),
    ]
