# Generated by Django 5.0.2 on 2024-04-22 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0011_alter_club_club_cover_alter_club_manager"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Activity_Form",
            new_name="ActivityForm",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_imgage",
            new_name="event_image",
        ),
        migrations.AlterField(
            model_name="event",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
