# Generated by Django 5.0.2 on 2024-04-22 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0012_rename_activity_form_activityform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="faq",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="rule",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
