# Generated by Django 5.0.2 on 2024-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0013_event_faq_event_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
