# Generated by Django 5.0.2 on 2024-04-24 00:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0014_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="about",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="purpose",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=40),
        ),
    ]
