# Generated by Django 5.0.2 on 2024-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0015_alter_club_about_alter_club_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="club_imgage",
            field=models.ImageField(
                blank=True, default="logo_club.png", upload_to="club_images"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_image",
            field=models.ImageField(
                blank=True, default="club-pic.jpeg", upload_to="event_images"
            ),
        ),
    ]
