# Generated by Django 4.2.11 on 2024-04-28 11:58

import club_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0016_alter_club_club_imgage_alter_event_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(
                max_length=200,
                null=True,
                validators=[club_pages.models.validate_length],
            ),
        ),
    ]
