# Generated by Django 4.2.11 on 2024-04-29 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club_pages", "0018_alter_activityform_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
