# Generated by Django 4.2.11 on 2024-05-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0023_activityform_status_event_status_alter_event_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club_pages.club",
            ),
        ),
    ]
