# Generated by Django 4.2.11 on 2024-05-02 15:44

import ckeditor.fields
import club_pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club_pages", "0024_alter_event_club"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "event_image",
                    models.ImageField(
                        blank=True,
                        default="club-pic.jpeg",
                        null=True,
                        upload_to="event_images",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=40, null=True)),
                ("first_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[club_pages.models.validate_length],
                    ),
                ),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("rule", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("faq", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "waiting"),
                            ("ACCEPTED", "accepted"),
                            ("REJECTED", "rejected"),
                        ],
                        default="WAITING",
                        max_length=50,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club_pages.club",
                    ),
                ),
            ],
        ),
    ]
