# Generated by Django 4.2.11 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0025_eventedit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="last_name",
        ),
        migrations.AddField(
            model_name="eventedit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
