# Generated by Django 4.2.11 on 2024-05-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0026_remove_event_first_name_remove_event_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventedit",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club_pages.event",
            ),
        ),
    ]
