# Generated by Django 4.2.11 on 2024-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0029_event_updated_at_eventedit_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING", "waiting"),
                    ("ACCEPTED", "accepted"),
                    ("REJECTED", "rejected"),
                ],
                default="WAITING",
                max_length=50,
                null=True,
            ),
        ),
    ]
