# Generated by Django 4.2.11 on 2024-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0030_alter_event_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityform",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="activityform",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="activityform",
            name="club",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="activityform",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITING", "waiting"),
                    ("ACCEPTED", "accepted"),
                    ("REJECTED", "rejected"),
                ],
                default="WAITING",
                max_length=50,
            ),
        ),
    ]
