# Generated by Django 4.2.11 on 2024-05-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0031_remove_activityform_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityform",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club_pages.club",
            ),
        ),
    ]
