# Generated by Django 4.2.11 on 2024-05-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0032_alter_activityform_club"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="club_imgage",
            new_name="club_image",
        ),
    ]
