# Generated by Django 4.2.11 on 2024-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0033_rename_club_imgage_club_club_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventedit",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images"),
        ),
    ]
