# Generated by Django 4.2.11 on 2024-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0034_alter_eventedit_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventedit",
            name="event_image",
            field=models.ImageField(
                blank=True, default="club-pic.jpeg", null=True, upload_to="event_images"
            ),
        ),
    ]
