# Generated by Django 4.2.11 on 2024-05-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0035_alter_eventedit_event_image"),
        ("club_pages", "0035_alter_notification_recipient"),
    ]

    operations = []
