# Generated by Django 4.2.11 on 2024-05-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0036_merge_20240508_0109"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
