# Generated by Django 4.2.11 on 2024-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_pages", "0037_activityform_updated_at_club_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=70),
        ),
    ]
